services:
  storage:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
    - 10000:10000
    - 10001:10001
    - 10002:10002

  otel:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    ports:
    - 18888:18888
    - 4317:18889
    environment:
    - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true