name: Teardown

on:
  workflow_dispatch:

jobs:
  deploy:
    environment: prod
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Sign in to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_DEPLOYMENT_APP_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_DEPLOYMENT_APP_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_DEPLOYMENT_APP_SUBSCRIPTION_ID }}

    - name: Remove Deployed Infrastructure
      run: |
        az stack group delete --resource-group rg-content-reading-agent --name content-reading-agent --action-on-unmanage deleteAll --yes |& tee ./stack-delete.json
        [ $PIPESTATUS -eq 0 ] || exit $PIPESTATUS
    
    - name: Debugging
      run: cat ./stack-delete.json
